name: Build AutoPacer
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MinHook Static
      run: vcpkg install minhook:x64-windows-static
      
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -A x64
      
    - name: Build DLL
      run: cmake --build build --config Release
      
    - name: Upload Finished DLL
      uses: actions/upload-artifact@v4
      with:
        name: AutoPacer-DLL
        path: build/Release/AutoPacer.dll
